name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Step 2: hello world
      - name: Print hello world
        run: echo "hello world"

      # Step 4: sample test
      - name: Run tests
        run: echo sampletest
