name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      EntryMessage:
        description: asdf
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: hello world
      - name: Print hello world
        run: echo "hello world"

      # Step 3: sample test
      - name: Run tests
        run: echo sampletest

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: Approvers
    steps:
      - name: Test
        run: echo "Approvers done"
